apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
  namespace: jenkins
spec:
  containers:
    - name: golang
      image: golang:alpine
      command:
        - sleep
      args: 
        - 99d
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2
    - name: docker
      image: docker:20.10.8
      command:
        - sleep
      args: 
        - 99d
      tty: true
      privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: helm
      image: dtzar/helm-kubectl:3.6.3
      command:
        - sleep
      args: 
        - 99d
      tty: true
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: m2
      hostPath:
        path: /root/.m2